application: marco-stahl
version: 1
runtime: python
api_version: 1

handlers:
- url: (.*)/
  static_files: static\1/index.html
  upload: static/*  
- url: /
  static_dir: static
- url: /.*
  static_files: static/page-not-found.html
  upload: static/*
  
  
